### ISSUE TITLE
Practice Lab 4.1: Work with segments - Segment creation stuck at getting ready

### ISSUE THREAD

**Issue by ArturoBravo111** [MicrosoftLearning/MB-220-Dynamics365forMarketing#59] opened 2024-04-19 05:19 UTC
# Module: 04
#### Step: 12

Description of issue

As mentioned in a previous issue: https://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing/issues/56

Segment status reason has been stuck at getting ready for more than one hour. Also, the mentioned copilot prompt doesn't work. 
![Screenshot 2024-04-19 171835](https://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing/assets/34762894/0a9bfcef-aa9a-4a5d-b24d-d22a878c301c)

Repro steps:

1. Create the segment
2. Status stuck at getting ready for more than one hour.

**Comment by ArturoBravo111** [comment] 2024-04-19 08:59
After further testing, I noticed segment creation works well with one group only. The moment a second group is included, status reason remains stuck for hours. Any ideas?

**Comment by anjenni** [comment] 2024-04-19 15:53
Got it, thanks Arturo - I'll retest this one. Does it finally work after an hour, or does it never go live?

**Comment by ArturoBravo111** [comment] 2024-04-19 20:40
Hi, after more than 20 hours, it's still stuck. Some Copilot prompts don't work either. 

I used multiple trial instances, and observed the same results.

**Comment by anjenni** [comment] 2024-04-25 21:24
@ArturoBravo111 Hi Arturo - I can't figure out what the issue is here but I've logged a bug with the product group and will continue to retest to see if it gets fixed. In the meantime, I've changed the lab to only include 1 group, so it should work in the meantime. I'm going to keep the issue open until I hear back.

Thanks again for logging this!

**Comment by anjenni** [comment] 2024-10-30 16:15
Closing - cannot recreate in most recent product update so marking as resolved.

**Closed** 2024-10-30 16:14 UTC
